import ctypes
import pytest

#pjr = ctypes.CDLL('./car_parks.so')
datetime = ctypes.CDLL('./datetime.so')

class Time(ctypes.Structure):
    _fields_ = [("hours", ctypes.c_int),
                ("minutes", ctypes.c_int)]

class Date(ctypes.Structure):
    _fields_ = [("year", ctypes.c_int),
                ("month", ctypes.c_int),
                ("day", ctypes.c_int)]

#pjr.create_parking.argtypes = [ctypes.c_char_p, ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int]
#pjr.create_parking.restype = ctypes.c_int

#pjr.number_plate_check.argtypes = [ctypes.c_char_p]
#pjr.number_plate_check.restype = ctypes.c_int

datetime.contatempo.argtypes = [Date, Time, Date, Time]

#class Test_create_parking:
#
#	def test_create_parking(self):
#		parkname = b"MyPark"
#		capacity = 8765
#		price_15 = 1332
#		price_15_1hour = 203
#		price_dailymax = 50
#		
#		result = pjr.create_parking(parkname, capacity, price_15, price_15_1hour, price_dailymax)
#		assert result == 0
#
#	def test_create_parking_invalid_capacity(self):
#		parkname = b"MyPark"
#		capacityneg = -3908
#		price_15 = 1332
#		price_15_1hour = 203
#		price_dailymax = 50
#		
#		error =	pjr.create_parking(parkname, capacityneg, price_15, price_15_1hour, price_dailymax)
#		assert error == 1
#
#	def test_create_parking_invalid_price(self):
#		parkname = b"iubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsy"
#		capacity = 123
#		price_15 = -234
#		price_15_1hour = -203
#		price_dailymax = -50
#
#		error = pjr.create_parking(parkname, capacity, price_15, price_15_1hour, price_dailymax)
#		assert error == 1
#
#	def test_create_parking_same_name(self):
#		parkname = b"iubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsyiubeilubfuyerguibuwefrtyhgfdvtyhjgbftdyhjgbvfsgrhfsdhggrefgdhsbjfuyghuhgyhdbjufgyhuifghvbyugvhygfvhyfvyfvhygfvhgyjfhvyfgvhygfvhygtfgvhuytfgvhygtfgvhytfcgvhygfcvhygfvhytfgcvhytfgcvhytfgcvhytfgcvhyftgcvhyfdtxgctdrsxfresdresderwazderdxfcgvhbjugjbkiuhjkhgvbjhgvjuytfgctdrfxrtsefredsxfdcgvhvhbjujbnhjvbjhugvfdsfgchvsjfdfvfdgsbhjbceyrigbhdfbvgueislrgyfsdhkvdfhjguerycbfgsdjdbgfyrssbvfgsgdhjffgryubsvghdbvhsvbyrcbhbfdvsbryvbdfhsgyurgteryutgykudsbvfhrykhrkyyrgsyjgfkyusergbcfrvybvrygfsy"
#		capacity = 123
#		price_15 = 234
#		price_15_1hour = 203
#		price_dailymax = 50
#
#		error1 = pjr.create_parking(parkname, capacity, price_15, price_15_1hour, price_dailymax)
#		error2 = pjr.create_parking(parkname, capacity, price_15, price_15_1hour, price_dailymax)
#		assert error1 == 0
#		assert error2 == 1

#class Test_number_plate_check:
#
#	def test_number_plate_check_mt1(self):
#		
#		result =  pjr.number_plate_check(b'AA-09-ZZ')
#		assert result == 0
#
#	def test_number_plate_check_mt2(self):
#		result = pjr.number_plate_check(b'00-23-ZZ')
#		assert result == 0
#   
#	def test_number_plate_check_mt3(self):
#		result = pjr.number_plate_check(b'BZ-23-90')
#		assert result == 0
#   
#	def test_number_plate_check_mt4(self):
#		result = pjr.number_plate_check(b'00-DF-78')
#		assert result == 0
#
#	def test_number_plate_check_mt5 (self):
#		result = pjr.number_plate_check(b'00cDF-78')
#		assert result == 1


class Test_contatempo:

	def test_contatempo_1(self):
		ti = Time()
		ti.hours = 10
		ti.minutes = 50

		tf = Time()
		tf.hours = 12
		tf.minutes = 50

		di = Date()
		di.year = 2024
		di.month = 3
		di.day = 18

		df = Date()
		df.year = 2024
		df.month = 3
		df.day = 18


		result = datetime.contatempo(di, ti, df, tf)
		assert result == 120


	def test_contatempo_2(self):
		ti = Time()
		ti.hours = 23
		ti.minutes = 14

		tf = Time()
		tf.hours = 10
		tf.minutes = 35

		di = Date()
		di.year = 2023
		di.month = 8
		di.day = 23

		df = Date()
		df.year = 2023
		df.month = 8
		df.day = 27


		result = datetime.contatempo(di, ti, df, tf)
		assert result == 5001

	



