name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Python_Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential python pip
    
    - name: Install Phyton dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Build with GCC
      run: gcc -O3 -Wall -Wextra -Werror -Wno-unused-result -o proj1 *.c
      
    - name: Run tests
      run: pytest -v tests.py
      working-directory: ./